services:
  luacheck:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck
    volumes:
      - ./:/workspace:ro
    working_dir: /workspace
    command: ["."]
  luacheck-report:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck-report
    volumes:
      - ./:/workspace:ro
      - ./target:/reports
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "luacheck --formatter JUnit . > /reports/luacheck-junit.xml"]
  combat-log-parser:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/combat_log_parser:/app
      - ./code:/code
      - ./combat-logs:/combat-logs
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python parse_combat_logs.py \
          --logs-dir /combat-logs \
          --spellmap /code/SpellMap.lua
  combat-log-parser-report:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/combat_log_parser:/app
      - ./code:/code
      - ./combat-logs:/combat-logs
      - ./target:/target
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python parse_combat_logs.py \
          --spellmap /code/SpellMap.lua \
          --logs-dir /combat-logs \
          --output-dir /target/combat_log_parser_output
  verify-sounds:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_sounds:/app
      - ./assets/sounds/en:/assets
      - ./code:/code
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python verify_sounds.py \
          --sound-path /assets \
          --spellmap /code/SpellMap.lua \
          --spellavoidmap /code/SpellAvoidMap.lua
  verify-sounds-report:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_sounds:/app
      - ./assets/sounds/en:/assets
      - ./code:/code
      - ./target:/target
    working_dir: /app
    entrypoint: []
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        mkdir -p /target/verify_sounds_output &&
        python verify_sounds.py \
          --sound-path /assets \
          --spellmap /code/SpellMap.lua \
          --spellavoidmap /code/SpellAvoidMap.lua \
          --output-format detailed > /target/verify_sounds_output/verification_report.txt
  verify-spellmap:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_spellmap:/app
      - ./code:/code
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python verify_spellmap.py \
          --spellmap /code/SpellMap.lua \
          --spellavoidmap /code/SpellAvoidMap.lua
  verify-spellmap-report:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_spellmap:/app
      - ./code:/code
      - ./target:/target
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        mkdir -p /target/verify_spellmap_output &&
        python verify_spellmap.py \
          --spellmap /code/SpellMap.lua \
          --spellavoidmap /code/SpellAvoidMap.lua > /target/verify_spellmap_output/verification_report.txt
