services:
  luacheck:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck
    volumes:
      - ./:/workspace:ro
    working_dir: /workspace
    command: ["."]
    init: true

  luacheck-report:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck-report
    volumes:
      - ./:/workspace:ro
      - ./target:/reports
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "luacheck --formatter JUnit . > /reports/luacheck-junit.xml"]
    init: true
