services:
  luacheck:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck
    volumes:
      - ./:/workspace:ro
    working_dir: /workspace
    command: ["."]
  luacheck-report:
    image: ragedunicorn/luacheck:1.2.0-alpine3.22.1-1
    container_name: pvpwarn-luacheck-report
    volumes:
      - ./:/workspace:ro
      - ./target:/reports
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "luacheck --formatter JUnit . > /reports/luacheck-junit.xml"]
  verify-sounds:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_sounds:/app
      - ./assets/sounds/en:/assets
      - ./code:/code
    working_dir: /app
    entrypoint: [ ]
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        python verify_sounds.py \
          --sound-path /assets \
          --spell-map /code/SpellMap.lua \
          --spell-avoid-map /code/SpellAvoidMap.lua
  verify-sounds-report:
    image: ragedunicorn/python:3-alpine3.22.1-1
    volumes:
      - ./tools/verify_sounds:/app
      - ./assets/sounds/en:/assets
      - ./code:/code
      - ./target:/target
    working_dir: /app
    entrypoint: []
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt &&
        mkdir -p /target/verify_sounds_output &&
        python verify_sounds.py \
          --sound-path /assets \
          --spell-map /code/SpellMap.lua \
          --spell-avoid-map /code/SpellAvoidMap.lua \
          --output-format detailed > /target/verify_sounds_output/verification_report.txt
